title = "Finely Tuned Technology Inc."
description = "Enhance your living space with Vancouver's experienced team of certified smart automation technologists. Brilliant™, ButterflyMX™ and THX Certified. "
languageCode = "en-ca"
baseURL = "/"
DefaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
gtm = "GTM-T2757SM"
servicename = "Home Automation Specialist"
googlemap = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2600.174078753291!2d-123.17132518425437!3d49.32992297534308!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54866f7ea187d183%3A0xa531c5ca655e8aba!2sFinely%20Tuned%20Technologies!5e0!3m2!1sen!2sca!4v1624565464925!5m2!1sen!2sca"
sitename = "Finely Tuned Technologies"
usebasin = "https://usebasin.com/f/72a7b6ac08d4"
videoOn = true
description = "Enhance your living space with Vancouver's experienced team of certified smart automation technologists. Brilliant™, ButterflyMX™ and THX Certified. "

[params.schema]
ogimage = "/img/home-automation-og.jpg"
logofooter = "/img/fttlogo.webp"
city = "West Vancouver"
logo = "/img/fttlogo.webp"
reservation = true
phone = "+1-604-619-3323"
priceRange = "$$$"
region = "BC"
country = "Canada"
postalcode = "V7V 1K3"
type = "ProfessionalService"
openinghour = "Mo-Sa: 9-17"
email = "info@fttech.ca"
address1 = "2 - 2130 Marine Drive, "
address2 = "#"
address_toggle = true

[params.social]
facebook = "#"
twitter = "#"
pinterest = "#"
instagram = "#"
linkedin = "#"

[[params.hours]]
hours = "Mon to Sat: 9AM to 5PM"

[[params.hours]]
hours = "Sun: CLOSED"

[module]

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "./node_modules/alpinejs/dist/alpine.js"
target = "assets/js/alpine.js"

[[module.mounts]]
source = "./node_modules/lazysizes/lazysizes.js"
target = "assets/js/lazysizes.js"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"

[build]
writeStats = true
enableRobotsTXT = false

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = "1"

[[menu.main]]
name = "About"
url = "about/"
weight = "2"

[[menu.main]]
name = "Services"
url = "services/"
weight = "3"

[[menu.main]]
name = "Testimonials"
url = "testimonials/"
weight = "4"

[[menu.main]]
name = "Contact"
url = "contact/"
weight = "5"

[[menu.main]]
name = "Free Consultation"
url = "free-consultation/"
weight = "6"